### Build settings ###

exclude:
  - README.md
  - 'node_modules'
  - 'scripts'
  - 'vendor'
  - out
  - capture
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - LICENSE
  - CNAME

## Site metadata ##

title: Bryan Sills's Dumb Website
